version: '3' 

services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb-container
    ports:
      - "27017:27017"

  nodeapp:
    build:
      context: .
    container_name: my-nodeapp-container
    ports:
      - "4000:4000"  # Map host port to container port
    depends_on:
      - mongodb  # Ensure MongoDB container is started before this one
