export const data = [
  {
    name: 'Discover the Fountain of Youth',
    description:
      'Embark on an epic adventure to find the legendary Fountain of Youth',
    status: 'In Progress',
    priority: 'High',
    assignee: 'Captain Jack Sparrow',
    createdAt: '2023-01-10T08:00:00Z',
    updatedAt: '2023-01-15T12:30:00Z'
  },
  {
    name: 'Build a Floating City',
    description:
      'Create a sustainable and self-sufficient city that floats on water',
    status: 'In Progress',
    priority: 'High',
    assignee: 'Architect Aquarius',
    createdAt: '2023-01-12T09:15:00Z',
    updatedAt: '2023-01-17T14:20:00Z'
  },
  {
    name: 'Train Dragons',
    description: 'Establish a dragon training academy and tame wild dragons',
    status: 'In Progress',
    priority: 'High',
    assignee: 'Hiccup Horrendous Haddock III',
    createdAt: '2023-01-15T10:30:00Z',
    updatedAt: '2023-01-20T11:45:00Z'
  },
  {
    name: 'Crack the Enigma Code',
    description:
      'Decode encrypted messages generated by the Enigma machine during World War II',
    status: 'Done',
    priority: 'High',
    assignee: 'Alan Turing',
    createdAt: '2023-01-18T13:20:00Z',
    updatedAt: '2023-01-22T15:55:00Z'
  },
  {
    name: 'Create a Real-Life Jurassic Park',
    description:
      'Bring dinosaurs back to life and create a dinosaur theme park',
    status: 'In Progress',
    priority: 'High',
    assignee: 'Dr. John Hammond',
    createdAt: '2023-01-20T16:10:00Z',
    updatedAt: '2023-01-23T17:40:00Z'
  },
  {
    name: 'Defend Earth Against Alien Invasion',
    description: "Lead Earth's defense against an imminent alien invasion",
    status: 'Done',
    priority: 'High',
    assignee: 'Commander Shepard',
    createdAt: '2023-01-25T09:45:00Z',
    updatedAt: '2023-01-29T14:55:00Z'
  },
  {
    name: 'Establish a Colony on Mars',
    description: 'Plan and build a sustainable human colony on the red planet',
    status: 'Done',
    priority: 'High',
    assignee: 'Elon Musk',
    createdAt: '2023-01-30T08:30:00Z',
    updatedAt: '2023-02-03T12:10:00Z'
  },
  {
    name: 'Unlock the Secrets of the Bermuda Triangle',
    description:
      'Investigate the mysteries and disappearances in the Bermuda Triangle',
    status: 'In Progress',
    priority: 'Low',
    assignee: 'Dr. Lara Croft',
    createdAt: '2023-02-05T11:20:00Z',
    updatedAt: '2023-02-09T16:25:00Z'
  },
  {
    name: 'Build a Robot Army',
    description:
      'Design and construct an army of advanced robots for various tasks',
    status: 'In Progress',
    priority: 'High',
    assignee: 'Dr. Isaac Asimov',
    createdAt: '2023-02-10T10:15:00Z',
    updatedAt: '2023-02-14T14:45:00Z'
  },
  {
    name: 'Explore the Deepest Part of the Ocean',
    description:
      'Descend to the Mariana Trench and explore its uncharted depths',
    status: 'In Progress',
    priority: 'High',
    assignee: 'Jacques Cousteau',
    createdAt: '2023-02-15T13:50:00Z',
    updatedAt: '2023-02-19T17:30:00Z'
  },
  {
    name: 'Colonize the Moon',
    description:
      'Establish a lunar base for scientific research and human habitation',
    status: 'In Progress',
    priority: 'High',
    assignee: 'Dr. Neil Armstrong',
    createdAt: '2023-02-20T09:40:00Z',
    updatedAt: '2023-02-24T12:55:00Z'
  },
  {
    name: 'Solve the Riemann Hypothesis',
    description:
      'Prove one of the most famous unsolved problems in mathematics',
    status: 'In Progress',
    priority: 'Low',
    assignee: 'Dr. Bernhard Riemann',
    createdAt: '2023-02-25T10:30:00Z',
    updatedAt: '2023-03-01T14:20:00Z'
  },
  {
    name: 'Travel to Parallel Universes',
    description:
      'Develop a method to explore alternate dimensions and parallel universes',
    status: 'In Progress',
    priority: 'Low',
    assignee: 'Dr. Stephen Hawking',
    createdAt: '2023-03-02T11:15:00Z',
    updatedAt: '2023-03-06T16:10:00Z'
  },
  {
    name: 'Create a Self-Aware AI Companion',
    description:
      'Build an AI companion capable of understanding and interacting with humans',
    status: 'In Progress',
    priority: 'High',
    assignee: 'Dr. Samantha Carter',
    createdAt: '2023-03-07T12:05:00Z',
    updatedAt: '2023-03-11T15:45:00Z'
  }
]
